backend: # This setting is required.
  name: git-gateway # test-repo
  branch: master
media_folder: public/img # The media_folder option specifies the folder path where uploaded files should be saved, relative to the base of the repo. This setting is required.
public_folder: /img # This is needed for Next to properly access the public folder
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: sgrvl
    api_key: 474894817422344
collections: # This setting is required.
  - name: "blog" # Unique identifier for the collection, used as the key when referenced in other contexts
    label: "Blog Posts" # Label for the collection in the editor UI; defaults to the value of name
    label_singular: "Blog Post" #Singular label for certain elements in the editor; defaults to the value of label
    folder: "posts" # Represent one or more files with the same format, fields, and configuration options, all stored within the same folder in the repository.
    create: true # Allows users to create new items in the collection; defaults to false
    slug: "{{slug}}" # Filename template
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Simon Gravel",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "LL",
          picker_utc: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
    editor:
      preview: false
